
package ec.espe.edu.ec.lab26.gui;

import ec.edu.espe.controller.Projectile;
import java.awt.Color;
import javax.swing.JTextField;

/**
 *
 * @author bryan
 */
public class FRMProjectile extends javax.swing.JFrame {

    /**
     * Creates new form Projectile
     */
    public FRMProjectile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblX = new javax.swing.JLabel();
        lblVo = new javax.swing.JLabel();
        txtVelocity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtAngle = new javax.swing.JTextField();
        lblXmax = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblX.setText("X=");
        getContentPane().add(lblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        lblVo.setText("Vo=");
        getContentPane().add(lblVo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtVelocity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVelocityActionPerformed(evt);
            }
        });
        txtVelocity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVelocityKeyPressed(evt);
            }
        });
        getContentPane().add(txtVelocity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, 56, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/lab26/images/projectil.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 430, 220));

        jLabel1.setText("Ángulo=");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        txtAngle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAngleKeyPressed(evt);
            }
        });
        getContentPane().add(txtAngle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 60, -1));
        getContentPane().add(lblXmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 90, 20));

        btnCalculate.setText("Calcular");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVelocityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVelocityActionPerformed
       
    }//GEN-LAST:event_txtVelocityActionPerformed

    private void txtVelocityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVelocityKeyPressed
        char validar = evt.getKeyChar();
        this.verificationJustNumbers(validar, txtVelocity);
    }//GEN-LAST:event_txtVelocityKeyPressed

    private void txtAngleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAngleKeyPressed
        char validar = evt.getKeyChar();
        this.verificationJustNumbers(validar, txtAngle);
    }//GEN-LAST:event_txtAngleKeyPressed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        Projectile projectile =new Projectile();
        
        projectile.setInicialVelocity(Float.parseFloat(txtVelocity.getText()));
        projectile.setAngle(Double.parseDouble(txtAngle.getText()));
        projectile.calculateDistance();
        lblXmax.setText(String.valueOf(projectile.getX()));
        projectile.savetoFile();
        
    }//GEN-LAST:event_btnCalculateActionPerformed

    
       public void verificationJustNumbers(char charValidation, JTextField nameOfTheTextField)
    {
        if(Character.isDigit(charValidation))
        {
            nameOfTheTextField.setBackground(Color.WHITE);
        }
        else
        {
            nameOfTheTextField.setBackground(Color.red);
            
        }
    }    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMProjectile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMProjectile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMProjectile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMProjectile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMProjectile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblVo;
    private javax.swing.JLabel lblX;
    private javax.swing.JLabel lblXmax;
    private javax.swing.JTextField txtAngle;
    private javax.swing.JTextField txtVelocity;
    // End of variables declaration//GEN-END:variables
}
